name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: npm install
    - name: test
      run: npm run test -- --watchAll=false
    - name: build
      run: npm run build

